insert into artist (name) values
 ('Jackie Wilson')
,('Stevie Wonder')
,('The Temptations')
,('The Four Tops')
,('Al Green')
,('Junior Walker')
,('Tom Jones')
,('Prince')
,('Bruno Mars')
,('Michael Jackson')
,('Aretha Franklin')
,('Diana Ross')
,('Smokey Robinson')
,('Ben E King')
,('Santana')
,('The Contours')
,('Kool & The Gang')
,('James Brown')
,('Marvin Gaye')
,('The Supremes')
,('Earth, Wind & Fire')
,('K.C. and The Sunshine Band')
,('Tower of Power')
,('Sam & Dave')
,('The Blues Brothers')
,('B.B. King')
,('Albert King')
,('Robert Johnson')
,('Led Zeppelin')
,('Tom Petty')
,('Credence Clearwater Revival')
,('Roberta Flack')
,('Bad Company')
,('Otis Redding')
,('The Trammps')
,('The O''Jays')
,('The Commodores')
,('Martha and the Vandellas')
,('The Miracles')
,('Tammi Terrel')
,('Mary Wells')
,('The Jackson 5')
,('Rick James')
,('Frankie Valli')
,('The Four Seasons')
,('The Pointer Sisters')
;
